### ISSUE TITLE
lrcclib sync with popuplyrics

### ISSUE THREAD

**Issue by MeviDiRaizel** [spicetify/cli#3132] opened 2024-08-08 13:42 UTC
### 📝 Provide a description of the new feature

as the title stated should support lrcclib lyric to sync with popuplyrics. since it only gets the lyrics from the other sources like musixmatch and others but lrcclib.

### ➕ Additional Information

![image_2024-08-08_214122041](https://github.com/user-attachments/assets/df5fef42-ee82-48e1-91da-16c0a6b6721b)
![image](https://github.com/user-attachments/assets/615b3758-96dd-4ef9-9ea2-900e5669407e)
![image_2024-08-08_214208809](https://github.com/user-attachments/assets/5216a66e-fe24-472e-8a90-e93d31a68f33)

**Comment by BEST8OY** [comment] 2024-08-09 14:18
One of the reasons I suggested a popup mode for Lyric Plus was this. (Popuplyric not supporting LRCLIB)
https://github.com/spicetify/cli/issues/3117

**Comment by Lseoksee** [comment] 2024-08-11 11:11
> One of the reasons I suggested a popup mode for Lyric Plus was this. (Popuplyric not supporting LRCLIB) #3117 Lyric Plus and Popuplyrics are not related. It would have been nice if Popuplyrics used Lyric plus implementation instead of its own.

Many developers are focusing on Lyric-plus and popuplyrics is often neglected. At the time of the lrcclib patch, I confirmed that it was not applied to popuplyrics, and I wanted to apply the changes to popuplyrics and make a pull request, but I didn't actually do it. I hope that the patch is made so that the lyrics provider can be managed as a separate component and used in the same way as popuplyrics and popuplyrics. Right now, both Lyric-plus and popuplyrics are implemented separately, so there are too many cases where developers neglect one side.

**Comment by rxri** [comment] 2024-08-11 13:12
> I hope that the patch is made so that the lyrics provider can be managed as a separate component and used in the same way as popuplyrics and popuplyrics

It won't. Popuplyrics won't use lyrics-plus. Popuplyrics won't be implemented into lyrics-plus. They are both separate entities which cannot be combined.

**Closed** 2024-08-26 17:19 UTC
Labels: 🔴 custom app, 🔵 extension
