### ISSUE TITLE
Issues after latest update (IT IS NOT ONLY A THEME ISSUE, RXRI STOP CLOSING IT WITHOUT READING IT ALL)

### ISSUE THREAD

**Issue by Veran04** [spicetify/cli#3180] opened 2024-09-24 21:04 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: 2.38.3
```

### 📝 Description

After the most recent spotify update causing my UI to break, I did the same steps I usually take which are:

Open command line
type "spicetify update"
Typically this is all I have to do and then my theme is reapplied. However in this case, the theme was applied in a very buggy way. You can see in the attached image that the panel on the right hand side (now playing view) takes up half the screen, and the bar you would typically drag to resize this does not work. I also get an error about needing to run the command spicetify sidebar_config 0 so I tried that and reapplied which made me stop receiving the error message but did not fix any of the UI issues. My extensions (shuffle+) are also not working currently.

THE SHUFFLE+ EXTENSION ALSO DOES NOT WORK EVEN WITH NO THEMES

THE SHUFFLE+ EXTENSION ALSO DOES NOT WORK EVEN WITH NO THEMES

THE SHUFFLE+ EXTENSION ALSO DOES NOT WORK EVEN WITH NO THEMES

RXRI PLEASE STOP CLOSING AND SAYING "THEME ISSUE" please either tell me where tf to post it or help, this is infuriating. its not a theme issue lol.

### 📸 Screenshots

![{9CB10C0A-84A4-46C5-BF9E-2D1BB5795C19}](https://github.com/user-attachments/assets/b160aacd-010f-4736-bb17-102ae656f283)

**Comment by rxri** [comment] 2024-09-24 21:07
Duplicate of https://github.com/spicetify/cli/issues/3177. Spicetify does not support 1.2.47. I also don't know what latest means.

Make a new issue again and you're getting banned off this org.

**Closed by rxri** 2024-09-24 21:07 UTC
Labels: 🐛 bug, 🔵 extension
