### ISSUE TITLE
Custom Apps misaligned

### ISSUE THREAD

**Issue by zhngharry** [spicetify/cli#3055] opened 2024-06-01 17:26 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e

- Spicetify version: Spicetify v2.36.11
```

### 📝 Description

Ever since setting up Spicetify, the Custom App Sidebar Logos and Titles are misaligned/ have missing padding.

I don't know if I did something wrong during setup or if others have this issue aswell.

### 📸 Screenshots

![image](https://github.com/spicetify/cli/assets/98264403/73743c32-c23f-4ee0-b937-6da12a1c6f5c)

**Comment by rxri** [comment] 2024-06-01 17:34
Duplicate of https://github.com/spicetify/cli/issues/3045

**Closed by rxri** 2024-06-01 17:34 UTC
Labels: 🐛 bug

**Comment by ohitstom** [comment] 2024-06-01 17:43
what is the discovery+ app?
