### ISSUE TITLE
spotify just shows blank screen when applying colors

### ISSUE THREAD

**Issue by daveningfr** [spicetify/cli#3183] opened 2024-09-26 16:06 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version:2.38.3
```

### 📝 Description

https://github.com/user-attachments/assets/66f7e792-0c55-4fd7-964c-5c4008e112e7

i just installed spicetify and spotify onto this arch install. i reinstalled arch as there was some bugs and prior to reinstalling spicetify colors was still working fine. but when i reinstalled arch and therefore reinstalled spicetify and spotify this happends. i checked spicetify colors and my colors where showing up. i think this is a version error but i dont know how to fix it please help. the video cut off but when i run spotify it was all right except no custom colors

to reproduce:
install latest versions of both spotify and spicetify
run any theme
open spotify 

what i expected to happen:
to have my colors in spotify change

**Comment by rxri** [comment] 2024-09-26 16:10
Duplicate of https://github.com/spicetify/cli/issues/3177

**Closed by rxri** 2024-09-26 16:10 UTC
Labels: 🐛 bug

**Comment by rxri** [comment] 2024-09-26 16:12
also that issue is not colors related at all lol

**Comment by daveningfr** [comment] 2024-09-26 16:13
sorry im just a newbie i just started customizing like 1 month ago

**Comment by rxri** [comment] 2024-09-26 16:15
that looks like perms file issue

**Comment by daveningfr** [comment] 2024-09-26 16:17
wait so is this a duplicate of #3177 or not?

**Comment by daveningfr** [comment] 2024-09-26 16:32
how do i fix it? can you provide relevant issues or something because i search everywhere but i cannot find  any solution that works for me please help.

**Comment by rxri** [comment] 2024-09-26 16:45
Discord server exists to help in situations like this, but i'm 99.99% sure it's not spicetify problem, but issue on your end
