### ISSUE TITLE
spotify doesnt work after the first update of v2.38.5

### ISSUE THREAD

**Issue by AxwinX** [spicetify/cli#3232] opened 2024-12-03 15:44 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.51.345.gcc39d911
- Spicetify version: v2.38.5
- Theme: marketplace
- Extensions: adblock.js, power-bar.js, copy-lyrics.js, beautiful-lyrics.mjs
- Custom apps: marketplace
```

### 📝 Description

after updating to spicetify v2.38.5 spotify is in a disabled state, cant play songs, cant access playlist, does this have anything to do with spotify banning mod apps ? [ actually went into experimental mode ]

but restoring/disabling [spicetify restore] spicetify then later applying spicetify [spicetify apply] works fine for now idk how long it will run.

### 📸 Screenshots

app  after the first update!
![image](https://github.com/user-attachments/assets/8d7b5f9b-b784-4b8d-a4ec-dc9534cf735b)

after restore and re-applying spicetify!
![image](https://github.com/user-attachments/assets/beb2dba3-a9db-4731-94bf-ac60101facca)
![image](https://github.com/user-attachments/assets/4f380e07-5cf2-4902-9542-331e6501912a)

**Comment by sanoojes** [comment] 2024-12-04 17:05
This sometimes happens when Spotify fails to load correctly and is resolved by reloading the Spotify.

I don't think this was caused by the update.

**Comment by rxri** [comment] 2024-12-04 23:44
That's spotify client (the Platform code) being shitty. Not related to spicetify.

**Closed by rxri** 2024-12-04 23:44 UTC
Labels: 🐛 bug, 🔴 custom app
