### ISSUE TITLE
Something went wrong. Refresh the page

### ISSUE THREAD

**Issue by Oleha1** [spicetify/cli#3244] opened 2024-12-21 03:00 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: -
- Spicetify version: 2.38.6
```

### 📝 Description

endless reboot page. appears when installing any extension, theme, script, application from the market, I tried to fix it myself but could not. The problem appeared after updating Spicetify. as it manifested itself after launching Spofity my theme did not load. I wrote Spicetify backup apply and after rebooting I got this window.

**Comment by rxri** [comment] 2024-12-21 03:00
Duplicate of https://github.com/spicetify/cli/issues/3243

**Closed by rxri** 2024-12-21 03:00 UTC
Labels: 🐛 bug, 🔵 extension
