### ISSUE TITLE
Using Spicetify causes "something went wrong" on start

### ISSUE THREAD

**Issue by Tomatofarmer444** [spicetify/cli#3246] opened 2024-12-21 12:01 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.53.438.g246d60c9
- Spicetify version: 2.38.6
```

### 📝 Description

App can only be accessed by using `spicetify restore backup`, otherwise spotify will just show something went wrong. doesnt matter how many times it is reloaded. My personal guess is that spicetify isnt supported fully yet.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/1b16e28d-0e7c-4b51-8187-67728e7970a1)

**Comment by AVABUK11** [comment] 2024-12-21 12:04
Same for me today too after a Spotify update, while it's broken I'm going to use it normally, hope it can get fixed

**Comment by PassiHD2004** [comment] 2024-12-21 12:16
Same for me. I tried reinstalling everything, but still broken.

**Comment by daplon** [comment] 2024-12-21 12:16
Same here:

Spotify para Windows (64 bits)
1.2.53.438.g246d60c9


![image](https://github.com/user-attachments/assets/7e3f029b-2a54-441d-9fec-0c0fb2b2937c)

**Comment by hitsvrr** [comment] 2024-12-21 12:17
same

**Comment by AVABUK11** [comment] 2024-12-21 12:17
im just using normal for now

**Comment by daplon** [comment] 2024-12-21 12:22
> im just using normal for now

Did you update Spotify to versión "1.2.53.438.g246d60c9"

**Comment by onijuiku** [comment] 2024-12-21 12:25
on the error page of your spotify, your plugins i think should still work, just go on your phone and connect to your pc app, and control your pc app through your phone, so you can still have ad blocker lol

**Comment by sakkarose** [comment] 2024-12-21 12:38
try to join a jam then it will be back normal

**Comment by daplon** [comment] 2024-12-21 12:41
> try to join a jam then it will be back normal

Or I can try to get a level 27 fire rune and try it with great faith.

**Comment by FoxyLoon** [comment] 2024-12-21 12:58
yeah, same here.

I'm also having other problems with spotify:
- Whenever I add a song of my choice to the playlist (right-click on the respective song, select “Add to queue”), spotify just refuses to play it. 
The interface continues to work, but spotify doesn't play any song that I individually add to the queue. However, if I select a playlist at random or not, it works. Only individual songs added by the user don't work. (this is happening since the last update)

- Whenever the next or previous song comes up (whether I change the song or not), the sidebar doesn't work properly. In other words, the images of the song albums are not updated whenever the song changes in the sidebar. It's just a visual thing because the sound is still fine. It only changes in the sidebar when I reload spotify. This is quite frequent, it only rarely works properly. (this is happening for a long time but it feels worse and more common with every update ;-;)

**Comment by jcmljunior** [comment] 2024-12-21 13:38
Working for me.
```
spicetify restore backup
spicetify upgrade
```

**Comment by FoxyLoon** [comment] 2024-12-21 13:49
> Working for me.
> 
> ```
> spicetify restore backup
> spicetify upgrade
> ```

unfortunately, not for me

**Comment by PassiHD2004** [comment] 2024-12-21 14:17
> > Working for me.
> > 
> > ```
> > spicetify restore backup
> > spicetify upgrade
> > ```
> 
> unfortunately, not for me

seems to be a race condition, sometimes its fine, just hit reload until it works

**Comment by sugarycherri** [comment] 2024-12-21 14:31
yeahh, having this issue too. seems to work fine for the most part unless i try to queue something. then it breaks again loll

**Comment by Agent5055** [comment] 2024-12-21 14:40
Same

**Comment by gdob** [comment] 2024-12-21 15:03
Looks like a duplicate issue, please see https://github.com/spicetify/cli/issues/3243. You can [downgrade to the previous version of Spotify](https://github.com/spicetify/cli/issues/3243#issuecomment-2557248555), then disable auto update for the time being by doing `spicetify spotify-updates block`. Then apply spicetify as usual. This info is coming from the devs on the Discord channel.

**Comment by onijuiku** [comment] 2024-12-21 15:14
> Looks like a duplicate issue, please see #3243. You can [downgrade to the previous version of Spotify](https://github.com/spicetify/cli/issues/3243#issuecomment-2557248555), then disable auto update for the time being by doing `spicetify spotify-updates block`. Then apply spicetify as usual. This info is coming from the devs on the Discord channel.

how would one downgrade

**Comment by rxri** [comment] 2024-12-21 16:16
Duplicate of #3243.

**Closed by rxri** 2024-12-21 16:16 UTC
Labels: 🐛 bug, 🔴 custom app
