### ISSUE TITLE
No sidebar config or Shuffle+ settings/buttons

### ISSUE THREAD

**Issue by Aisper** [spicetify/cli#3182] opened 2024-09-26 07:47 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.47.364.gf06e5cee
- Spicetify version: v2.38.3
Windows
```

### 📝 Description

After latest update there's almost nothing from spicetify except theme. RMB menu doesn't contain shuffle+ option, there's no shuffle+ or sidebar config options in their usual places

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/f705b960-a6c2-4fb6-ba4b-3c9665ad6ca6)
![image](https://github.com/user-attachments/assets/6e3f43c3-8dc4-4187-a8a2-129bf8fba88f)

**Comment by rxri** [comment] 2024-09-26 13:12
Duplicate of #3177

**Closed by rxri** 2024-09-26 13:12 UTC
Labels: 🐛 bug, 🔵 extension
