### ISSUE TITLE
Spicetify Dont Work.

### ISSUE THREAD

**Issue by 0x73616D** [spicetify/cli#3181] opened 2024-09-25 22:01 UTC
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bits) 1.2.47.364.gf06e5cee
- Spicetify version: spicetify v2.38.3
```

### 📝 Description

Hi, I updated Spotify and Spicetify stopped working, I'm using Windows 11, commands like "Spicetify upgrade", "Spicetify Backup apply" and similar don't work because they keep loading infinitely, does anyone have a solution for this?

**Comment by machinemessiah** [comment] 2024-09-25 22:45
Spicetify doesn't support Spotify 1.2.47 presently, see [here](https://github.com/spicetify/cli/issues/3177#issuecomment-2371439460) for more info.

**Comment by rxri** [comment] 2024-09-26 02:32
Duplicate of #3177

**Closed by rxri** 2024-09-26 02:32 UTC
Labels: 🐛 bug
